import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import { ApolloWrapper } from "@/lib/ApolloWrapper";
import Header from "@/components/Header";
import StyledComponentsRegistry from "@/lib/registry";
import UserProvider from "../lib/UserContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          <ApolloWrapper>
            <StyledComponentsRegistry>
              <Header />
              {children}
            </StyledComponentsRegistry>
          </ApolloWrapper>
        </UserProvider>
      </body>
    </html>
  );
}
